services:
  app:
    build:
      context: .
    container_name: otp-gesex-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
